In [1]:
import gym
from Environment import halite_env as Env

In [2]:
help(Env)

Help on module Environment.halite_env in Environment:

NAME
    Environment.halite_env

CLASSES
    builtins.object
        MapGenerator
    gym.core.Env(builtins.object)
        HaliteEnv
    
    class HaliteEnv(gym.core.Env)
     |  HaliteEnv(num_players, map_type, map_size, regen_map_on_reset=False)
     |  
     |  Stores the Halite III OpenAI gym environment.
     |  
     |  [Original, to change]
     |  This environment does not use Halite III's actual game engine
     |  (which analyzes input from terminal and is slow for RL) but instead is
     |  a replica in Python.
     |  
     |  Attributes:
     |  -----------
     |  self.map : np.ndarray
     |      Map of game as a 3D array. Stores different information on each "layer"
     |      of the array.
     |  Layer 0: The Halite currently on the sea floor
     |  Layer 1: The Halite currently on ships/factory/dropoff
     |  Layer 2: Whether a Factory or Dropoff exists at the layer (Factory is 1, Dropoff is -1)
     |  Laye

In [3]:
env = Env.HaliteEnv(1, None, 6) #remove None once fetched the update from upstream

Initializing Halite Environment


In [4]:
env.map[:,:,0] #halite in the map

array([[9947, 9373, 5035, 8025,   40,  668],
       [7054, 3024, 9908, 7287, 2641, 2959],
       [ 415, 6382, 1927, 5282, 6980,  754],
       [5567, 4358, 4021,    0, 7720, 5974],
       [ 975, 6982,  700, 7289, 7204, 4040],
       [2934, 2029, 7908, 1429, 2472, 3992]])

In [5]:
env.map[:,:,1] #halite carried from each ship

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [6]:
env.map[:,:,2] #shipyard position

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [10]:
env.map[:,:,3] #ship position

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [9]:
env.map[:,:,3][env.map[:,:,2].astype(bool)] = 1

In [8]:
env.step()

TypeError: step() missing 1 required positional argument: 'action'