# Halite challenge - basics

In [21]:
import gym
import numpy as np
from Environment import halite_env as Env

In [123]:
from importlib import reload
reload(Env)

<module 'Environment.halite_env' from '/home/nicola/Nicola_unipd/QuartoAnno/TODO/Baiesi/RL/haliteRL/Environment/halite_env.py'>

## Setup of the environment

In [141]:
num_players = 1
n_actions = 5 # no dropoffs, 1 action for staying still, 4 for moving in the cardinal directions
map_size = 6 # 6 x 6 map

In [142]:
env = Env.HaliteEnv(num_players, map_size)

Initializing Halite Environment


In [143]:
# halite in the map, min = 0, max = 1000
env.map[:,:,0]

array([[151, 147, 124, 551,  82, 261],
       [767, 343, 715, 610, 474, 178],
       [ 98, 115, 471, 335, 364, 165],
       [927, 656, 242,   0, 740, 307],
       [566, 194, 124,  22,  49, 983],
       [366, 818, 486, 414,  85, 768]])

In [137]:
# shows the halite carried from each ship in the position corresponding to the ship
# initially there is 
env.map[:,:,1] 

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [138]:
env.map[:,:,2] #shipyard position

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [139]:
env.map[:,:,3] #ship position

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [140]:
print("Initial halite: ", env.player_halite[0])

Initial halite:  [5000.]


In [127]:
 
action = np.full((map_size,map_size), -1)

In [128]:
env.step(action, makeship=True)

State with mask:  [1]


array([[[154,   0,   0,   0],
        [853,   0,   0,   0],
        [174,   0,   0,   0],
        [585,   0,   0,   0],
        [550,   0,   0,   0],
        [707,   0,   0,   0]],

       [[145,   0,   0,   0],
        [818,   0,   0,   0],
        [505,   0,   0,   0],
        [113,   0,   0,   0],
        [373,   0,   0,   0],
        [788,   0,   0,   0]],

       [[180,   0,   0,   0],
        [983,   0,   0,   0],
        [797,   0,   0,   0],
        [876,   0,   0,   0],
        [565,   0,   0,   0],
        [911,   0,   0,   0]],

       [[215,   0,   0,   0],
        [346,   0,   0,   0],
        [177,   0,   0,   0],
        [  0,   0,   1,   1],
        [193,   0,   0,   0],
        [573,   0,   0,   0]],

       [[167,   0,   0,   0],
        [917,   0,   0,   0],
        [675,   0,   0,   0],
        [355,   0,   0,   0],
        [787,   0,   0,   0],
        [736,   0,   0,   0]],

       [[519,   0,   0,   0],
        [890,   0,   0,   0],
        [620,   0,   0,   0],
