# Halite challenge - basics

In [145]:
import gym
import numpy as np
from Environment import halite_env as Env

In [146]:
from importlib import reload
reload(Env)

<module 'Environment.halite_env' from '/home/nicola/Nicola_unipd/QuartoAnno/TODO/Baiesi/RL/haliteRL/Environment/halite_env.py'>

## Setup of the environment

In [161]:
num_players = 1
n_actions = 5 # no dropoffs, 1 action for staying still, 4 for moving in the cardinal directions
map_size = 6 # 6 x 6 map

In [162]:
env = Env.HaliteEnv(num_players, map_size)

Initializing Halite Environment


In [163]:
# halite in the map, min = 0, max = 1000
env.map[:,:,0]

array([[ 402,   13, 2058,  129, 6605, 2519],
       [8485, 5365, 4391, 6920, 3923, 1609],
       [7096,  908, 7907,   55, 7688, 4625],
       [9496,  391, 6336,    0, 8390, 3738],
       [ 533, 6331, 2326, 9347, 6103, 3737],
       [4315, 8487, 1605, 3464, 6772, 2550]])

In [151]:
# shows the halite carried from each ship in the position corresponding to the ship
# initially there is no ship, hence no halite carried either
env.map[:,:,1] 

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [152]:
# shipyard position
env.map[:,:,2] 

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [155]:
# ship position
env.map[:,:,3] 

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [154]:
print("Initial halite: ", env.player_halite[0])

Initial halite:  [5000.]


In [158]:
# actions are represented as a matrix whose entries are -1 if no ship is in that position, 
#'a_i' if ship i is present in that position 
action_matrix = np.full((map_size,map_size), -1) # no ship, no action

In [160]:
# the environment already has in memory the last state, thus we don't need to resubmit it
# the only things that we submit are the action matrix and the shipyard action (1 or True to spawn a ship, 0 otherwise)
shipyard_action = 1
# returns the state
s = env.step(action_matrix, makeship = shipyard_action)