# Halite 

## 

In [1]:
import gym
import time
import numpy as np
import matplotlib.pyplot as plt
import sys
sys.path.insert(0, "../Environment/")
import halite_env as Env


In [2]:
from importlib import reload
reload(Env)


<module 'halite_env' from '../Environment/halite_env.py'>

In [3]:
num_players = 1
map_size = 7 # 7 x 7 map

In [4]:
HEnv = Env.HaliteEnv(num_players, map_size)

In [5]:
def Single_ship_env_initialization(map_size, num_players = 1):
    HEnv = Env.HaliteEnv(num_players, map_size)
    return Env.SingleShipEnv(HEnv, 1, map_size)

def check_position(env):
    print(env.state[:,:,:])


In [6]:
env = Single_ship_env_initialization(map_size)
print(np.swapaxes(env.reset(), 0, 2))
check_position(env)
env.render()
#env.render().shape

[[[755 612  80 492 590 641  79]
  [150 833 889 614 228 915   7]
  [ 26 397 518  69 689 134  80]
  [295 609 618   0 259  55 915]
  [387 354 453 483 513 795   2]
  [166 955 200 218 457 299 981]
  [450 391 536 253 361 743 942]]

 [[  0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0]
  [  0   0   0   1   0   0   0]
  [  0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0]]

 [[  0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0]]

 [[  0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0]
  [  0   0   0   1   0   0   0]
  [  0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0]]

 [[  0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0]


In [7]:
env.step(1)
check_position(env)
state = env.state

[[[755   0   0   0   0]
  [150   0   0   0   0]
  [ 26   0   0   0   0]
  [295   0   0   0   0]
  [387   0   0   0   0]
  [166   0   0   0   0]
  [450   0   0   0   0]]

 [[612   0   0   0   0]
  [833   0   0   0   0]
  [397   0   0   0   0]
  [609   0   0   0   0]
  [354   0   0   0   0]
  [955   0   0   0   0]
  [391   0   0   0   0]]

 [[ 80   0   0   0   0]
  [889   0   0   0   0]
  [518   0   0   0   0]
  [618   0   0   0   0]
  [453   0   0   0   0]
  [200   0   0   0   0]
  [536   0   0   0   0]]

 [[492   0   0   0   0]
  [614   0   0   0   0]
  [ 69   0   0   0   0]
  [  0   0   0   1   0]
  [483   0   0   0   0]
  [218   0   0   0   0]
  [253   0   0   0   0]]

 [[590   0   0   0   0]
  [228   0   0   0   0]
  [689   0   0   0   0]
  [259   1   0   0   1]
  [513   0   0   0   0]
  [457   0   0   0   0]
  [361   0   0   0   0]]

 [[641   0   0   0   0]
  [915   0   0   0   0]
  [134   0   0   0   0]
  [ 55   0   0   0   0]
  [795   0   0   0   0]
  [299   0   0   0   0]
  [743

In [8]:
#np.nonzero(state[:,:,1])
#import emoji
#state[:,:,0]
#print(halite[1])
import emoji

In [9]:
halite = ([i for i in range(map_size) for j in range(map_size)],[j for i in range(map_size) for j in range(map_size)])
ships = np.nonzero(state[:,:,1])
cargo = np.nonzero(state[:,:,2])
factories = np.nonzero(state[:,:,3])

for _ in range(map_size):
    print('+-----', end='')
print('+', end='\n')
for i in range(map_size):

    for j in range(map_size):
        H = state[halite[0][i*map_size+j],halite[1][i*map_size+j],0]
        if H < 10:
            print('|   \x1b[2;35;46m{}\x1b[0m '.format(H), end='')
        elif H < 100:
            print('|  \x1b[2;35;46m{}\x1b[0m '.format(H), end='')
        else:
            print('| \x1b[2;35;46m{}\x1b[0m '.format(H), end='')
        
    print('|', end='\n')
    for j in range(map_size):
        print('|  ', end='')
        A = i in factories[1] and j in factories[0]
        B = i in ships[1] and j in ships[0]
        if A and B:
            print('🏰⛵️', end='')
        elif A:
            print('🏰 ', end='')
        elif B:
            print('⛵️ ', end='')
        else:
            print('   ', end='')
        
    print('|', end ='\n')
    for j in range(map_size):
        A = i in ships[1] and j in ships[0]
        B = i in cargo[1] and j in cargo[0]
        if A and B:
            C = state[cargo[0][i*map_size+j],cargo[1][i*map_size+j],2]
            if C < 10:
                print('|   \x1b[1;30;41m{}\x1b[0m '.format(C), end='')
            elif C < 100:
                print('|  \x1b[1;30;41m{}\x1b[0m '.format(C), end='')
            else:
                print('| \x1b[1;30;41m{}\x1b[0m '.format(C), end='')
        elif A:
            print('|  \x1b[1;30;41m0\x1b[0m  ', end='')
        else:
            print('|     ', end='')

    print('|', end='\n')
    
    for _ in range(map_size):
        print('+-----', end='')
    print('+', end='\n')

        
print('\033[93m'+"ooook"+'\033[0m')


+-----+-----+-----+-----+-----+-----+-----+
| 755 | 150 |  26 | 295 | 387 | 166 | 450 |
|     |     |     |     |     |     |     |
|     |     |     |     |     |     |     |
+-----+-----+-----+-----+-----+-----+-----+
| 612 | 833 | 397 | 609 | 354 | 955 | 391 |
|     |     |     |     |     |     |     |
|     |     |     |     |     |     |     |
+-----+-----+-----+-----+-----+-----+-----+
|  80 | 889 | 518 | 618 | 453 | 200 | 536 |
|     |     |     |     |     |     |     |
|     |     |     |     |     |     |     |
+-----+-----+-----+-----+-----+-----+-----+
| 492 | 614 |  69 |   0 | 483 | 218 | 253 |
|     |     |     |  🏰 |  ⛵️ |     |     |
|     |     |     |     |  0  |     |     |
+-----+-----+-----+-----+-----+-----+-----+
| 590 | 228 | 689 | 259 | 513 | 457 | 361 |
|     |     |     |     |     |     |     |
|     |     |     |     |     |     |     |
+-----+-----+-----+-----+-----+-----+-----+
| 641 | 915 | 134 |  55 | 795 | 299 | 743 |
|     |     |     |     |     |  

## Baselines

In [10]:
from stable_baselines.common.policies import MlpPolicy
from stable_baselines.common.vec_env import DummyVecEnv, SubprocVecEnv
from stable_baselines.common import set_global_seeds
from stable_baselines import PPO2, ACKTR
import stable_baselines
import tensorflow as tf
reload(stable_baselines)
#from stable_baselines.logger import configure
#configure("/home/mango/Documents/haliteRL/tensorboard_ppo2", ['stdout','log','csv','tensorboard'])


MULTI = False
COMPARISON = False
obs_type = "raw"
n_timesteps = int(1e7)
map_size = 7

In [11]:
def make_env(map_size, rank, seed=1234):
    """
    Utility function for multiprocessed env.

    :param env_id: (str) the environment ID
    :param rank: (int) index of the subprocess
    :param seed: (int) the inital seed for RNG
    """

    def _init():
        env = Single_ship_env_initialization(map_size)
        env.seed(seed + rank)
        return env

    set_global_seeds(seed)
    return _init

def evaluate(model, num_steps=1000):
    """
    Evaluate a RL agent
    :param model: (BaseRLModel object) the RL Agent
    :param num_steps: (int) number of timesteps to evaluate it
    :return: (float) Mean reward
    """
    episode_rewards = [[0.0] for _ in range(env.num_envs)]
    obs = env.reset()
    for i in range(num_steps):
        # _states are only useful when using LSTM policies
        actions, _states = model.predict(obs)
        # here, action, rewards and dones are arrays
        # because we are using vectorized env
        obs, rewards, dones, info = env.step(actions)

        # Stats
        for j in range(env.num_envs):
            episode_rewards[j][-1] += rewards[j]
            if dones[j]:
                episode_rewards[j].append(0.0)

    mean_rewards = [0.0 for _ in range(env.num_envs)]
    n_episodes = 0
    for i in range(env.num_envs):
        mean_rewards[i] = np.mean(episode_rewards[i])
        n_episodes += len(episode_rewards[i])

    # Compute mean reward
    mean_reward = round(np.mean(mean_rewards), 1)
    print("Mean reward:", mean_reward, "Num episodes:", n_episodes)

    return mean_reward


def callback(locs, globs):
    hlt = locs['self'].env.env_method('pl_halite')
    print(hlt)
    tf.summary.scalar('Player_halite', hlt[0])
    merged = tf.summary.merge_all()
    train_writer = tf.summary.FileWriter('./tensorboard_ppo2/', sess.graph)

    return True


if MULTI:
    num_cpu = 32  # Number of processes to use
    # Create the vectorized environment
    env = SubprocVecEnv([make_env(map_size, i) for i in range(num_cpu)])
else:
    # env = SingleSnek(obs_type="rgb", n_food=3)
    env = Single_ship_env_initialization(map_size)
    # The algorithms require a vectorized environment to run
    env = DummyVecEnv([lambda: env])


ob = env.reset()



In [12]:
model = stable_baselines.PPO2(MlpPolicy, env, verbose=1, tensorboard_log="./tensorboard_ppo2/")


Instructions for updating:
Use keras.layers.flatten instead.
Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.


In [13]:
mean_reward_before_train = evaluate(model, num_steps=1000)

Mean reward: -34.2 Num episodes: 3


In [14]:
if MULTI:
    # Multiprocessed RL Training
    start_time = time.time()
    model.learn(n_timesteps)
    total_time_multi = time.time() - start_time

    print(
        "Took {:.2f}s for multiprocessed version - {:.2f} FPS".format(
            total_time_multi, n_timesteps / total_time_multi
        )
    )
    
    if COMPARISON:
        # Single Process RL Training
        env = Single_ship_env_initialization(map_size)
        env = DummyVecEnv([lambda: env])

        single_process_model = PPO2(MlpPolicy, env, verbose=0)

        start_time = time.time()
        single_process_model.learn(n_timesteps)
        total_time_single = time.time() - start_time

        print(
            "Took {:.2f}s for single process version - {:.2f} FPS".format(
                total_time_single, n_timesteps / total_time_single
            )
        )

        print(
            "Multiprocessed training is {:.2f}x faster!".format(
                total_time_single / total_time_multi
            )
        )

    mean_reward = evaluate(model, num_steps=10000)
else:
    start_time = time.time()
    model.learn(n_timesteps, callback=callback)
    total_time_single = time.time() - start_time

    print(
        "Took {:.2f}s for training - {:.2f} FPS".format(
            total_time_single, n_timesteps / total_time_single
        )
    )

    mean_reward = evaluate(model, num_steps=10000)


--------------------------------------
| approxkl           | 0.00013025603 |
| clipfrac           | 0.0           |
| explained_variance | -0.231        |
| fps                | 290           |
| n_updates          | 1             |
| policy_entropy     | 1.386166      |
| policy_loss        | -0.0012364477 |
| serial_timesteps   | 128           |
| time_elapsed       | 2.38e-06      |
| total_timesteps    | 128           |
| value_loss         | 3.6016152     |
--------------------------------------
[array([4000.])]
--------------------------------------
| approxkl           | 8.0366546e-05 |
| clipfrac           | 0.0           |
| explained_variance | -0.0747       |
| fps                | 477           |
| n_updates          | 2             |
| policy_entropy     | 1.385502      |
| policy_loss        | -0.0012774965 |
| serial_timesteps   | 256           |
| time_elapsed       | 0.445         |
| total_timesteps    | 256           |
| value_loss         | 2.5544636     |
--------

[array([4000.])]
--------------------------------------
| approxkl           | 0.00076008687 |
| clipfrac           | 0.0           |
| explained_variance | -0.184        |
| fps                | 443           |
| n_updates          | 17            |
| policy_entropy     | 1.3393639     |
| policy_loss        | -0.0063008573 |
| serial_timesteps   | 2176          |
| time_elapsed       | 4.86          |
| total_timesteps    | 2176          |
| value_loss         | 0.6536979     |
--------------------------------------
[array([5000.])]
--------------------------------------
| approxkl           | 0.0006949943  |
| clipfrac           | 0.0           |
| explained_variance | -0.148        |
| fps                | 416           |
| n_updates          | 18            |
| policy_entropy     | 1.3140092     |
| policy_loss        | -0.0039142864 |
| serial_timesteps   | 2304          |
| time_elapsed       | 5.15          |
| total_timesteps    | 2304          |
| value_loss         | 0.76521

[array([4798.])]
--------------------------------------
| approxkl           | 0.00064091454 |
| clipfrac           | 0.001953125   |
| explained_variance | -0.49         |
| fps                | 443           |
| n_updates          | 33            |
| policy_entropy     | 1.1133368     |
| policy_loss        | -0.0032012297 |
| serial_timesteps   | 4224          |
| time_elapsed       | 9.47          |
| total_timesteps    | 4224          |
| value_loss         | 0.057049584   |
--------------------------------------
[array([7347.])]
--------------------------------------
| approxkl           | 0.0005310583  |
| clipfrac           | 0.0           |
| explained_variance | -7.01         |
| fps                | 453           |
| n_updates          | 34            |
| policy_entropy     | 1.1697947     |
| policy_loss        | -0.0016654879 |
| serial_timesteps   | 4352          |
| time_elapsed       | 9.77          |
| total_timesteps    | 4352          |
| value_loss         | 0.05424

[array([4460.])]
-------------------------------------
| approxkl           | 0.0015808893 |
| clipfrac           | 0.017578125  |
| explained_variance | -1.09        |
| fps                | 498          |
| n_updates          | 49           |
| policy_entropy     | 0.8252347    |
| policy_loss        | -0.011248026 |
| serial_timesteps   | 6272         |
| time_elapsed       | 13.8         |
| total_timesteps    | 6272         |
| value_loss         | 0.0022153296 |
-------------------------------------
[array([5095.])]
-------------------------------------
| approxkl           | 0.0005820569 |
| clipfrac           | 0.0          |
| explained_variance | -0.0634      |
| fps                | 470          |
| n_updates          | 50           |
| policy_entropy     | 0.8980596    |
| policy_loss        | 0.0016251319 |
| serial_timesteps   | 6400         |
| time_elapsed       | 14.1         |
| total_timesteps    | 6400         |
| value_loss         | 0.09808111   |
----------------

[array([5611.])]
--------------------------------------
| approxkl           | 0.00014599603 |
| clipfrac           | 0.0           |
| explained_variance | 0.0606        |
| fps                | 446           |
| n_updates          | 65            |
| policy_entropy     | 1.1871533     |
| policy_loss        | -0.0011475637 |
| serial_timesteps   | 8320          |
| time_elapsed       | 18.3          |
| total_timesteps    | 8320          |
| value_loss         | 1.6236476     |
--------------------------------------
[array([7026.])]
--------------------------------------
| approxkl           | 0.0008130632  |
| clipfrac           | 0.0           |
| explained_variance | -0.0769       |
| fps                | 492           |
| n_updates          | 66            |
| policy_entropy     | 1.174569      |
| policy_loss        | -0.0032713322 |
| serial_timesteps   | 8448          |
| time_elapsed       | 18.6          |
| total_timesteps    | 8448          |
| value_loss         | 0.22690

[array([6753.])]
-------------------------------------
| approxkl           | 0.0020802284 |
| clipfrac           | 0.00390625   |
| explained_variance | -1.75        |
| fps                | 448          |
| n_updates          | 81           |
| policy_entropy     | 1.2142416    |
| policy_loss        | -0.006451995 |
| serial_timesteps   | 10368        |
| time_elapsed       | 23           |
| total_timesteps    | 10368        |
| value_loss         | 0.011641227  |
-------------------------------------
[array([7965.])]
--------------------------------------
| approxkl           | 0.00081843435 |
| clipfrac           | 0.0           |
| explained_variance | -0.0158       |
| fps                | 482           |
| n_updates          | 82            |
| policy_entropy     | 1.2345998     |
| policy_loss        | -0.0031392977 |
| serial_timesteps   | 10496         |
| time_elapsed       | 23.3          |
| total_timesteps    | 10496         |
| value_loss         | 0.12076661    |
----

[array([6487.])]
-------------------------------------
| approxkl           | 0.0015700407 |
| clipfrac           | 0.0          |
| explained_variance | 0.0432       |
| fps                | 513          |
| n_updates          | 97           |
| policy_entropy     | 1.3410321    |
| policy_loss        | -0.000630621 |
| serial_timesteps   | 12416        |
| time_elapsed       | 27.6         |
| total_timesteps    | 12416        |
| value_loss         | 0.58425033   |
-------------------------------------
[array([4000.])]
--------------------------------------
| approxkl           | 0.00091820717 |
| clipfrac           | 0.0           |
| explained_variance | -0.0264       |
| fps                | 423           |
| n_updates          | 98            |
| policy_entropy     | 1.3193203     |
| policy_loss        | -0.008227313  |
| serial_timesteps   | 12544         |
| time_elapsed       | 27.9          |
| total_timesteps    | 12544         |
| value_loss         | 0.5744531     |
----

[array([6796.])]
-------------------------------------
| approxkl           | 0.0020021752 |
| clipfrac           | 0.0          |
| explained_variance | 0.132        |
| fps                | 479          |
| n_updates          | 113          |
| policy_entropy     | 1.296106     |
| policy_loss        | -0.008788336 |
| serial_timesteps   | 14464        |
| time_elapsed       | 32.2         |
| total_timesteps    | 14464        |
| value_loss         | 0.7446243    |
-------------------------------------
[array([5390.])]
--------------------------------------
| approxkl           | 0.0012454361  |
| clipfrac           | 0.00390625    |
| explained_variance | 0.199         |
| fps                | 495           |
| n_updates          | 114           |
| policy_entropy     | 1.2521791     |
| policy_loss        | 0.00031164475 |
| serial_timesteps   | 14592         |
| time_elapsed       | 32.5          |
| total_timesteps    | 14592         |
| value_loss         | 1.6434226     |
----

[array([4000.])]
--------------------------------------
| approxkl           | 0.001072396   |
| clipfrac           | 0.0           |
| explained_variance | -0.664        |
| fps                | 478           |
| n_updates          | 129           |
| policy_entropy     | 1.2995235     |
| policy_loss        | -0.0036489803 |
| serial_timesteps   | 16512         |
| time_elapsed       | 36.7          |
| total_timesteps    | 16512         |
| value_loss         | 0.041327346   |
--------------------------------------
[array([5166.])]
---------------------------------------
| approxkl           | 0.00065010414  |
| clipfrac           | 0.0            |
| explained_variance | 0.431          |
| fps                | 490            |
| n_updates          | 130            |
| policy_entropy     | 1.2846159      |
| policy_loss        | -0.00021546544 |
| serial_timesteps   | 16640          |
| time_elapsed       | 37             |
| total_timesteps    | 16640          |
| value_loss       

[array([4000.])]
--------------------------------------
| approxkl           | 0.0014507185  |
| clipfrac           | 0.0           |
| explained_variance | 0.0472        |
| fps                | 484           |
| n_updates          | 145           |
| policy_entropy     | 1.2465483     |
| policy_loss        | -0.0012813781 |
| serial_timesteps   | 18560         |
| time_elapsed       | 41            |
| total_timesteps    | 18560         |
| value_loss         | 0.4592516     |
--------------------------------------
[array([5125.])]
--------------------------------------
| approxkl           | 0.00058197754 |
| clipfrac           | 0.0           |
| explained_variance | -0.41         |
| fps                | 517           |
| n_updates          | 146           |
| policy_entropy     | 1.2440397     |
| policy_loss        | -0.001001835  |
| serial_timesteps   | 18688         |
| time_elapsed       | 41.3          |
| total_timesteps    | 18688         |
| value_loss         | 0.10028

[array([4000.])]
--------------------------------------
| approxkl           | 4.3363052e-05 |
| clipfrac           | 0.0           |
| explained_variance | -0.137        |
| fps                | 484           |
| n_updates          | 161           |
| policy_entropy     | 1.2657536     |
| policy_loss        | 0.0004970215  |
| serial_timesteps   | 20608         |
| time_elapsed       | 45.3          |
| total_timesteps    | 20608         |
| value_loss         | 2.5652204     |
--------------------------------------
[array([4000.])]
--------------------------------------
| approxkl           | 0.00040734754 |
| clipfrac           | 0.00390625    |
| explained_variance | 0.0532        |
| fps                | 505           |
| n_updates          | 162           |
| policy_entropy     | 1.2789448     |
| policy_loss        | -0.0033016242 |
| serial_timesteps   | 20736         |
| time_elapsed       | 45.6          |
| total_timesteps    | 20736         |
| value_loss         | 0.31869

[array([5579.])]
-------------------------------------
| approxkl           | 0.0030542514 |
| clipfrac           | 0.0          |
| explained_variance | 0.0845       |
| fps                | 470          |
| n_updates          | 177          |
| policy_entropy     | 1.2594811    |
| policy_loss        | -0.012664904 |
| serial_timesteps   | 22656        |
| time_elapsed       | 49.7         |
| total_timesteps    | 22656        |
| value_loss         | 1.5896883    |
-------------------------------------
[array([5579.])]
-------------------------------------
| approxkl           | 0.0015039534 |
| clipfrac           | 0.0          |
| explained_variance | 0.00226      |
| fps                | 481          |
| n_updates          | 178          |
| policy_entropy     | 1.2320596    |
| policy_loss        | 0.0020259058 |
| serial_timesteps   | 22784        |
| time_elapsed       | 50           |
| total_timesteps    | 22784        |
| value_loss         | 0.9817684    |
----------------

[array([4911.])]
--------------------------------------
| approxkl           | 5.3922042e-05 |
| clipfrac           | 0.0           |
| explained_variance | 0.122         |
| fps                | 488           |
| n_updates          | 193           |
| policy_entropy     | 1.2441251     |
| policy_loss        | 0.00029253226 |
| serial_timesteps   | 24704         |
| time_elapsed       | 54            |
| total_timesteps    | 24704         |
| value_loss         | 0.6211111     |
--------------------------------------
[array([5911.])]
--------------------------------------
| approxkl           | 0.00097755    |
| clipfrac           | 0.0           |
| explained_variance | -0.0138       |
| fps                | 518           |
| n_updates          | 194           |
| policy_entropy     | 1.2423515     |
| policy_loss        | -0.0045409417 |
| serial_timesteps   | 24832         |
| time_elapsed       | 54.3          |
| total_timesteps    | 24832         |
| value_loss         | 0.37594

[array([4559.])]
-------------------------------------
| approxkl           | 0.0028980337 |
| clipfrac           | 0.021484375  |
| explained_variance | -0.367       |
| fps                | 499          |
| n_updates          | 209          |
| policy_entropy     | 1.1025503    |
| policy_loss        | -0.013935358 |
| serial_timesteps   | 26752        |
| time_elapsed       | 58.3         |
| total_timesteps    | 26752        |
| value_loss         | 0.06814181   |
-------------------------------------
[array([4000.])]
--------------------------------------
| approxkl           | 0.001132969   |
| clipfrac           | 0.01171875    |
| explained_variance | 0.0613        |
| fps                | 472           |
| n_updates          | 210           |
| policy_entropy     | 1.139789      |
| policy_loss        | -0.0014562651 |
| serial_timesteps   | 26880         |
| time_elapsed       | 58.5          |
| total_timesteps    | 26880         |
| value_loss         | 0.00043878384 |
----

[array([7072.])]
---------------------------------------
| approxkl           | 0.00024334298  |
| clipfrac           | 0.0            |
| explained_variance | 5.96e-08       |
| fps                | 476            |
| n_updates          | 225            |
| policy_entropy     | 1.1275438      |
| policy_loss        | -0.00011435279 |
| serial_timesteps   | 28800          |
| time_elapsed       | 62.6           |
| total_timesteps    | 28800          |
| value_loss         | 0.14408022     |
---------------------------------------
[array([4551.])]
--------------------------------------
| approxkl           | 0.001498259   |
| clipfrac           | 0.0           |
| explained_variance | -1.19e-07     |
| fps                | 483           |
| n_updates          | 226           |
| policy_entropy     | 1.0989103     |
| policy_loss        | -0.0048419912 |
| serial_timesteps   | 28928         |
| time_elapsed       | 62.9          |
| total_timesteps    | 28928         |
| value_loss     

[array([9611.])]
---------------------------------------
| approxkl           | 0.00094399205  |
| clipfrac           | 0.0            |
| explained_variance | 0.00678        |
| fps                | 478            |
| n_updates          | 241            |
| policy_entropy     | 1.3553171      |
| policy_loss        | -0.00022704003 |
| serial_timesteps   | 30848          |
| time_elapsed       | 66.9           |
| total_timesteps    | 30848          |
| value_loss         | 1.0109972      |
---------------------------------------
[array([4000.])]
-------------------------------------
| approxkl           | 0.0001227936 |
| clipfrac           | 0.0          |
| explained_variance | 0.00245      |
| fps                | 470          |
| n_updates          | 242          |
| policy_entropy     | 1.3539379    |
| policy_loss        | 0.0010372536 |
| serial_timesteps   | 30976        |
| time_elapsed       | 67.2         |
| total_timesteps    | 30976        |
| value_loss         | 2.042

[array([4000.])]
-------------------------------------
| approxkl           | 0.0009836996 |
| clipfrac           | 0.0          |
| explained_variance | -0.0486      |
| fps                | 477          |
| n_updates          | 257          |
| policy_entropy     | 1.3095436    |
| policy_loss        | -0.00749193  |
| serial_timesteps   | 32896        |
| time_elapsed       | 71.2         |
| total_timesteps    | 32896        |
| value_loss         | 0.6368719    |
-------------------------------------
[array([5552.])]
-------------------------------------
| approxkl           | 0.0015577669 |
| clipfrac           | 0.01953125   |
| explained_variance | -0.0581      |
| fps                | 464          |
| n_updates          | 258          |
| policy_entropy     | 1.3132823    |
| policy_loss        | -0.008704292 |
| serial_timesteps   | 33024        |
| time_elapsed       | 71.5         |
| total_timesteps    | 33024        |
| value_loss         | 0.52341074   |
----------------

[array([5517.])]
--------------------------------------
| approxkl           | 0.00058675767 |
| clipfrac           | 0.0           |
| explained_variance | -0.0281       |
| fps                | 510           |
| n_updates          | 273           |
| policy_entropy     | 1.1950068     |
| policy_loss        | -0.004756371  |
| serial_timesteps   | 34944         |
| time_elapsed       | 75.5          |
| total_timesteps    | 34944         |
| value_loss         | 0.30939835    |
--------------------------------------
[array([5943.])]
--------------------------------------
| approxkl           | 0.0018335271  |
| clipfrac           | 0.0           |
| explained_variance | -0.0221       |
| fps                | 473           |
| n_updates          | 274           |
| policy_entropy     | 1.2518272     |
| policy_loss        | -0.0012960511 |
| serial_timesteps   | 35072         |
| time_elapsed       | 75.8          |
| total_timesteps    | 35072         |
| value_loss         | 0.44951

[array([5000.])]
---------------------------------------
| approxkl           | 0.00033074722  |
| clipfrac           | 0.0            |
| explained_variance | 0              |
| fps                | 474            |
| n_updates          | 289            |
| policy_entropy     | 0.94170797     |
| policy_loss        | -0.00094293617 |
| serial_timesteps   | 36992          |
| time_elapsed       | 80             |
| total_timesteps    | 36992          |
| value_loss         | 0.11198548     |
---------------------------------------
[array([7090.])]
--------------------------------------
| approxkl           | 0.0007537813  |
| clipfrac           | 0.0           |
| explained_variance | 0             |
| fps                | 499           |
| n_updates          | 290           |
| policy_entropy     | 0.90773576    |
| policy_loss        | -0.0031034048 |
| serial_timesteps   | 37120         |
| time_elapsed       | 80.3          |
| total_timesteps    | 37120         |
| value_loss     

[array([5121.])]
-------------------------------------
| approxkl           | 0.0031683198 |
| clipfrac           | 0.064453125  |
| explained_variance | 0            |
| fps                | 407          |
| n_updates          | 305          |
| policy_entropy     | 1.05647      |
| policy_loss        | -0.002516365 |
| serial_timesteps   | 39040        |
| time_elapsed       | 84.5         |
| total_timesteps    | 39040        |
| value_loss         | 0.011579768  |
-------------------------------------
[array([5437.])]
--------------------------------------
| approxkl           | 0.0010165689  |
| clipfrac           | 0.0           |
| explained_variance | 0             |
| fps                | 432           |
| n_updates          | 306           |
| policy_entropy     | 1.1073642     |
| policy_loss        | 0.00033605465 |
| serial_timesteps   | 39168         |
| time_elapsed       | 84.9          |
| total_timesteps    | 39168         |
| value_loss         | 0.18521912    |
----

[array([4931.])]
--------------------------------------
| approxkl           | 0.00037455617 |
| clipfrac           | 0.0           |
| explained_variance | 0             |
| fps                | 497           |
| n_updates          | 321           |
| policy_entropy     | 1.0989424     |
| policy_loss        | -0.0010306793 |
| serial_timesteps   | 41088         |
| time_elapsed       | 89            |
| total_timesteps    | 41088         |
| value_loss         | 1.1043843     |
--------------------------------------
[array([5931.])]
---------------------------------------
| approxkl           | 0.0001318316   |
| clipfrac           | 0.0            |
| explained_variance | -0.00191       |
| fps                | 462            |
| n_updates          | 322            |
| policy_entropy     | 1.0757118      |
| policy_loss        | -0.00010691432 |
| serial_timesteps   | 41216          |
| time_elapsed       | 89.2           |
| total_timesteps    | 41216          |
| value_loss       

[array([5927.])]
--------------------------------------
| approxkl           | 0.00089795416 |
| clipfrac           | 0.0           |
| explained_variance | 0.0597        |
| fps                | 467           |
| n_updates          | 337           |
| policy_entropy     | 1.026803      |
| policy_loss        | -0.003263414  |
| serial_timesteps   | 43136         |
| time_elapsed       | 93.7          |
| total_timesteps    | 43136         |
| value_loss         | 1.1657593     |
--------------------------------------
[array([4003.])]
-------------------------------------
| approxkl           | 0.0003944112 |
| clipfrac           | 0.0          |
| explained_variance | -0.628       |
| fps                | 469          |
| n_updates          | 338          |
| policy_entropy     | 1.0546317    |
| policy_loss        | -0.001620703 |
| serial_timesteps   | 43264        |
| time_elapsed       | 93.9         |
| total_timesteps    | 43264        |
| value_loss         | 0.055248782  |
---

[array([5796.])]
--------------------------------------
| approxkl           | 0.0017457444  |
| clipfrac           | 0.0           |
| explained_variance | 0.0337        |
| fps                | 477           |
| n_updates          | 353           |
| policy_entropy     | 1.2489806     |
| policy_loss        | -0.0030240847 |
| serial_timesteps   | 45184         |
| time_elapsed       | 98.1          |
| total_timesteps    | 45184         |
| value_loss         | 0.31068683    |
--------------------------------------
[array([5000.])]
--------------------------------------
| approxkl           | 0.0006670698  |
| clipfrac           | 0.0           |
| explained_variance | -2.33         |
| fps                | 473           |
| n_updates          | 354           |
| policy_entropy     | 1.2554954     |
| policy_loss        | -0.0005644695 |
| serial_timesteps   | 45312         |
| time_elapsed       | 98.4          |
| total_timesteps    | 45312         |
| value_loss         | 0.03435

[array([4000.])]
-------------------------------------
| approxkl           | 0.0011595541 |
| clipfrac           | 0.0          |
| explained_variance | -2.79        |
| fps                | 471          |
| n_updates          | 369          |
| policy_entropy     | 1.1773932    |
| policy_loss        | -0.007362707 |
| serial_timesteps   | 47232        |
| time_elapsed       | 102          |
| total_timesteps    | 47232        |
| value_loss         | 0.024132222  |
-------------------------------------
[array([5854.])]
--------------------------------------
| approxkl           | 0.0024866313  |
| clipfrac           | 0.0           |
| explained_variance | 0.0856        |
| fps                | 463           |
| n_updates          | 370           |
| policy_entropy     | 1.2360317     |
| policy_loss        | -0.0028311429 |
| serial_timesteps   | 47360         |
| time_elapsed       | 103           |
| total_timesteps    | 47360         |
| value_loss         | 1.041437      |
----

[array([4000.])]
-------------------------------------
| approxkl           | 0.0060673114 |
| clipfrac           | 0.064453125  |
| explained_variance | 0.0188       |
| fps                | 424          |
| n_updates          | 385          |
| policy_entropy     | 1.1259036    |
| policy_loss        | -0.021215474 |
| serial_timesteps   | 49280        |
| time_elapsed       | 107          |
| total_timesteps    | 49280        |
| value_loss         | 0.09334054   |
-------------------------------------
[array([5901.])]
--------------------------------------
| approxkl           | 0.003809664   |
| clipfrac           | 0.068359375   |
| explained_variance | -0.0879       |
| fps                | 430           |
| n_updates          | 386           |
| policy_entropy     | 1.0879087     |
| policy_loss        | -0.0069553195 |
| serial_timesteps   | 49408         |
| time_elapsed       | 107           |
| total_timesteps    | 49408         |
| value_loss         | 0.0043322514  |
----

[array([4736.])]
--------------------------------------
| approxkl           | 0.0006224315  |
| clipfrac           | 0.0           |
| explained_variance | 0.0433        |
| fps                | 401           |
| n_updates          | 401           |
| policy_entropy     | 1.3052444     |
| policy_loss        | -0.0015033602 |
| serial_timesteps   | 51328         |
| time_elapsed       | 112           |
| total_timesteps    | 51328         |
| value_loss         | 0.39379886    |
--------------------------------------
[array([7532.])]
------------------------------------
| approxkl           | 0.004060635 |
| clipfrac           | 0.046875    |
| explained_variance | 0.00891     |
| fps                | 480         |
| n_updates          | 402         |
| policy_entropy     | 1.2762487   |
| policy_loss        | -0.02195971 |
| serial_timesteps   | 51456       |
| time_elapsed       | 112         |
| total_timesteps    | 51456       |
| value_loss         | 0.22885561  |
---------------

[array([5037.])]
-------------------------------------
| approxkl           | 0.0011331073 |
| clipfrac           | 0.00390625   |
| explained_variance | -0.00866     |
| fps                | 470          |
| n_updates          | 417          |
| policy_entropy     | 1.3072803    |
| policy_loss        | 0.003101776  |
| serial_timesteps   | 53376        |
| time_elapsed       | 116          |
| total_timesteps    | 53376        |
| value_loss         | 1.1958417    |
-------------------------------------
[array([6037.])]
--------------------------------------
| approxkl           | 0.0014357276  |
| clipfrac           | 0.01171875    |
| explained_variance | 0.0236        |
| fps                | 423           |
| n_updates          | 418           |
| policy_entropy     | 1.3202251     |
| policy_loss        | -0.0033514043 |
| serial_timesteps   | 53504         |
| time_elapsed       | 116           |
| total_timesteps    | 53504         |
| value_loss         | 1.9838594     |
----

[array([5240.])]
--------------------------------------
| approxkl           | 0.0032175514  |
| clipfrac           | 0.06640625    |
| explained_variance | -0.0135       |
| fps                | 466           |
| n_updates          | 433           |
| policy_entropy     | 1.2029834     |
| policy_loss        | -0.0018528171 |
| serial_timesteps   | 55424         |
| time_elapsed       | 121           |
| total_timesteps    | 55424         |
| value_loss         | 0.6962926     |
--------------------------------------
[array([6544.])]
---------------------------------------
| approxkl           | 0.0014994962   |
| clipfrac           | 0.0            |
| explained_variance | -1.19e-07      |
| fps                | 440            |
| n_updates          | 434            |
| policy_entropy     | 1.2009046      |
| policy_loss        | -0.00021323538 |
| serial_timesteps   | 55552          |
| time_elapsed       | 121            |
| total_timesteps    | 55552          |
| value_loss       

[array([5542.])]
--------------------------------------
| approxkl           | 0.003058555   |
| clipfrac           | 0.015625      |
| explained_variance | 0.0037        |
| fps                | 447           |
| n_updates          | 449           |
| policy_entropy     | 1.2527218     |
| policy_loss        | -0.0061565926 |
| serial_timesteps   | 57472         |
| time_elapsed       | 125           |
| total_timesteps    | 57472         |
| value_loss         | 1.1191593     |
--------------------------------------
[array([4000.])]
-------------------------------------
| approxkl           | 0.001081568  |
| clipfrac           | 0.0          |
| explained_variance | -0.484       |
| fps                | 436          |
| n_updates          | 450          |
| policy_entropy     | 1.2733927    |
| policy_loss        | -0.003665288 |
| serial_timesteps   | 57600        |
| time_elapsed       | 125          |
| total_timesteps    | 57600        |
| value_loss         | 0.029216683  |
---

[array([7610.])]
-------------------------------------
| approxkl           | 0.0008473988 |
| clipfrac           | 0.0          |
| explained_variance | -0.0684      |
| fps                | 450          |
| n_updates          | 465          |
| policy_entropy     | 1.2690173    |
| policy_loss        | 0.0003538835 |
| serial_timesteps   | 59520        |
| time_elapsed       | 130          |
| total_timesteps    | 59520        |
| value_loss         | 0.30892766   |
-------------------------------------
[array([4773.])]
--------------------------------------
| approxkl           | 0.00047335832 |
| clipfrac           | 0.001953125   |
| explained_variance | 0             |
| fps                | 505           |
| n_updates          | 466           |
| policy_entropy     | 1.2792226     |
| policy_loss        | -0.0015287946 |
| serial_timesteps   | 59648         |
| time_elapsed       | 130           |
| total_timesteps    | 59648         |
| value_loss         | 0.29525265    |
----

[array([6691.])]
-------------------------------------
| approxkl           | 0.00059376   |
| clipfrac           | 0.0          |
| explained_variance | 5.96e-08     |
| fps                | 450          |
| n_updates          | 481          |
| policy_entropy     | 1.2940605    |
| policy_loss        | 0.0008583437 |
| serial_timesteps   | 61568        |
| time_elapsed       | 135          |
| total_timesteps    | 61568        |
| value_loss         | 0.11728413   |
-------------------------------------
[array([4857.])]
--------------------------------------
| approxkl           | 0.00028480456 |
| clipfrac           | 0.001953125   |
| explained_variance | -1.19e-07     |
| fps                | 465           |
| n_updates          | 482           |
| policy_entropy     | 1.2855371     |
| policy_loss        | -0.0021201074 |
| serial_timesteps   | 61696         |
| time_elapsed       | 135           |
| total_timesteps    | 61696         |
| value_loss         | 1.833181      |
----

[array([4964.])]
-------------------------------------
| approxkl           | 0.0021997874 |
| clipfrac           | 0.0078125    |
| explained_variance | -0.0378      |
| fps                | 460          |
| n_updates          | 497          |
| policy_entropy     | 1.3386335    |
| policy_loss        | -0.005558783 |
| serial_timesteps   | 63616        |
| time_elapsed       | 139          |
| total_timesteps    | 63616        |
| value_loss         | 0.07104867   |
-------------------------------------
[array([6511.])]
---------------------------------------
| approxkl           | 0.00051953644  |
| clipfrac           | 0.0            |
| explained_variance | -4.39          |
| fps                | 459            |
| n_updates          | 498            |
| policy_entropy     | 1.3458982      |
| policy_loss        | -0.00030353083 |
| serial_timesteps   | 63744          |
| time_elapsed       | 139            |
| total_timesteps    | 63744          |
| value_loss         | 0.0797498

[array([4000.])]
---------------------------------------
| approxkl           | 7.9871774e-05  |
| clipfrac           | 0.0            |
| explained_variance | 0.083          |
| fps                | 485            |
| n_updates          | 513            |
| policy_entropy     | 1.1584532      |
| policy_loss        | -0.00080949476 |
| serial_timesteps   | 65664          |
| time_elapsed       | 144            |
| total_timesteps    | 65664          |
| value_loss         | 2.144984       |
---------------------------------------
[array([5000.])]
--------------------------------------
| approxkl           | 0.00117389    |
| clipfrac           | 0.0           |
| explained_variance | 0.209         |
| fps                | 457           |
| n_updates          | 514           |
| policy_entropy     | 1.1568571     |
| policy_loss        | -0.0074263047 |
| serial_timesteps   | 65792         |
| time_elapsed       | 144           |
| total_timesteps    | 65792         |
| value_loss     

[array([4904.])]
-------------------------------------
| approxkl           | 0.0006266917 |
| clipfrac           | 0.0          |
| explained_variance | -0.00183     |
| fps                | 472          |
| n_updates          | 529          |
| policy_entropy     | 1.3001406    |
| policy_loss        | 0.0012343308 |
| serial_timesteps   | 67712        |
| time_elapsed       | 148          |
| total_timesteps    | 67712        |
| value_loss         | 3.920464     |
-------------------------------------
[array([4904.])]
---------------------------------------
| approxkl           | 0.00036386895  |
| clipfrac           | 0.0            |
| explained_variance | 0.0157         |
| fps                | 473            |
| n_updates          | 530            |
| policy_entropy     | 1.3138627      |
| policy_loss        | -0.00088171405 |
| serial_timesteps   | 67840          |
| time_elapsed       | 148            |
| total_timesteps    | 67840          |
| value_loss         | 0.8717396

[array([5466.])]
--------------------------------------
| approxkl           | 0.002090503   |
| clipfrac           | 0.015625      |
| explained_variance | 0.0392        |
| fps                | 496           |
| n_updates          | 545           |
| policy_entropy     | 1.2877277     |
| policy_loss        | -0.0045220563 |
| serial_timesteps   | 69760         |
| time_elapsed       | 152           |
| total_timesteps    | 69760         |
| value_loss         | 1.369028      |
--------------------------------------
[array([6806.])]
--------------------------------------
| approxkl           | 0.0011455083  |
| clipfrac           | 0.01171875    |
| explained_variance | -0.0168       |
| fps                | 483           |
| n_updates          | 546           |
| policy_entropy     | 1.275933      |
| policy_loss        | -0.0042703794 |
| serial_timesteps   | 69888         |
| time_elapsed       | 153           |
| total_timesteps    | 69888         |
| value_loss         | 0.91187

[array([5547.])]
-------------------------------------
| approxkl           | 0.0015766772 |
| clipfrac           | 0.0          |
| explained_variance | -0.191       |
| fps                | 460          |
| n_updates          | 561          |
| policy_entropy     | 1.156976     |
| policy_loss        | -0.004650661 |
| serial_timesteps   | 71808        |
| time_elapsed       | 157          |
| total_timesteps    | 71808        |
| value_loss         | 0.0169738    |
-------------------------------------
[array([6937.])]
--------------------------------------
| approxkl           | 0.0020491926  |
| clipfrac           | 0.017578125   |
| explained_variance | -0.00103      |
| fps                | 476           |
| n_updates          | 562           |
| policy_entropy     | 1.119773      |
| policy_loss        | -0.0048375363 |
| serial_timesteps   | 71936         |
| time_elapsed       | 157           |
| total_timesteps    | 71936         |
| value_loss         | 0.19591041    |
----

[array([6695.])]
--------------------------------------
| approxkl           | 0.00019328337 |
| clipfrac           | 0.0           |
| explained_variance | 0.0453        |
| fps                | 420           |
| n_updates          | 577           |
| policy_entropy     | 1.2250168     |
| policy_loss        | 0.00032950402 |
| serial_timesteps   | 73856         |
| time_elapsed       | 161           |
| total_timesteps    | 73856         |
| value_loss         | 0.18612242    |
--------------------------------------
[array([4000.])]
---------------------------------------
| approxkl           | 0.00068227336  |
| clipfrac           | 0.0            |
| explained_variance | -0.965         |
| fps                | 434            |
| n_updates          | 578            |
| policy_entropy     | 1.1855695      |
| policy_loss        | -0.00027667894 |
| serial_timesteps   | 73984          |
| time_elapsed       | 162            |
| total_timesteps    | 73984          |
| value_loss       

[array([7105.])]
-------------------------------------
| approxkl           | 0.0015717545 |
| clipfrac           | 0.0234375    |
| explained_variance | -0.00229     |
| fps                | 476          |
| n_updates          | 593          |
| policy_entropy     | 1.2543379    |
| policy_loss        | -0.009206432 |
| serial_timesteps   | 75904        |
| time_elapsed       | 166          |
| total_timesteps    | 75904        |
| value_loss         | 0.56874937   |
-------------------------------------
[array([5000.])]
------------------------------------
| approxkl           | 0.000981061 |
| clipfrac           | 0.005859375 |
| explained_variance | 0.0296      |
| fps                | 460         |
| n_updates          | 594         |
| policy_entropy     | 1.2832161   |
| policy_loss        | 0.003535042 |
| serial_timesteps   | 76032       |
| time_elapsed       | 166         |
| total_timesteps    | 76032       |
| value_loss         | 0.57878804  |
----------------------------

[array([4000.])]
-------------------------------------
| approxkl           | 0.000520782  |
| clipfrac           | 0.0          |
| explained_variance | 0.00627      |
| fps                | 472          |
| n_updates          | 609          |
| policy_entropy     | 1.1725533    |
| policy_loss        | 0.0003582217 |
| serial_timesteps   | 77952        |
| time_elapsed       | 171          |
| total_timesteps    | 77952        |
| value_loss         | 1.0661765    |
-------------------------------------
[array([5601.])]
--------------------------------------
| approxkl           | 0.0023140865  |
| clipfrac           | 0.013671875   |
| explained_variance | -1.19e-07     |
| fps                | 486           |
| n_updates          | 610           |
| policy_entropy     | 1.1304591     |
| policy_loss        | -0.0052471035 |
| serial_timesteps   | 78080         |
| time_elapsed       | 171           |
| total_timesteps    | 78080         |
| value_loss         | 0.034307405   |
----

[array([4000.])]
-------------------------------------
| approxkl           | 0.003017859  |
| clipfrac           | 0.037109375  |
| explained_variance | 1.19e-07     |
| fps                | 480          |
| n_updates          | 625          |
| policy_entropy     | 1.1288773    |
| policy_loss        | -0.011181713 |
| serial_timesteps   | 80000        |
| time_elapsed       | 175          |
| total_timesteps    | 80000        |
| value_loss         | 0.038837474  |
-------------------------------------
[array([6030.])]
--------------------------------------
| approxkl           | 0.0015737776  |
| clipfrac           | 0.0           |
| explained_variance | -1.19e-07     |
| fps                | 466           |
| n_updates          | 626           |
| policy_entropy     | 1.0172262     |
| policy_loss        | 0.00013945613 |
| serial_timesteps   | 80128         |
| time_elapsed       | 175           |
| total_timesteps    | 80128         |
| value_loss         | 0.0049321502  |
----

[array([5571.])]
--------------------------------------
| approxkl           | 0.0003499779  |
| clipfrac           | 0.0           |
| explained_variance | 0.0814        |
| fps                | 467           |
| n_updates          | 641           |
| policy_entropy     | 1.3073226     |
| policy_loss        | -0.0028089758 |
| serial_timesteps   | 82048         |
| time_elapsed       | 179           |
| total_timesteps    | 82048         |
| value_loss         | 0.03687545    |
--------------------------------------
[array([7245.])]
--------------------------------------
| approxkl           | 0.0015872477  |
| clipfrac           | 0.0           |
| explained_variance | 0.0141        |
| fps                | 474           |
| n_updates          | 642           |
| policy_entropy     | 1.2972541     |
| policy_loss        | -0.0063299327 |
| serial_timesteps   | 82176         |
| time_elapsed       | 180           |
| total_timesteps    | 82176         |
| value_loss         | 0.18293

[array([4696.])]
--------------------------------------
| approxkl           | 0.00019233259 |
| clipfrac           | 0.0           |
| explained_variance | 0.0712        |
| fps                | 498           |
| n_updates          | 657           |
| policy_entropy     | 1.0412667     |
| policy_loss        | -0.00350749   |
| serial_timesteps   | 84096         |
| time_elapsed       | 184           |
| total_timesteps    | 84096         |
| value_loss         | 0.07742216    |
--------------------------------------
[array([6980.])]
--------------------------------------
| approxkl           | 0.00096100825 |
| clipfrac           | 0.0           |
| explained_variance | -0.0991       |
| fps                | 456           |
| n_updates          | 658           |
| policy_entropy     | 1.0655935     |
| policy_loss        | -0.005190734  |
| serial_timesteps   | 84224         |
| time_elapsed       | 184           |
| total_timesteps    | 84224         |
| value_loss         | 0.56438

[array([4000.])]
--------------------------------------
| approxkl           | 7.685611e-05  |
| clipfrac           | 0.0           |
| explained_variance | 1.79e-07      |
| fps                | 473           |
| n_updates          | 673           |
| policy_entropy     | 0.94880605    |
| policy_loss        | -0.0008666082 |
| serial_timesteps   | 86144         |
| time_elapsed       | 188           |
| total_timesteps    | 86144         |
| value_loss         | 0.04487709    |
--------------------------------------
[array([5362.])]
--------------------------------------
| approxkl           | 0.00021216544 |
| clipfrac           | 0.0           |
| explained_variance | 0             |
| fps                | 430           |
| n_updates          | 674           |
| policy_entropy     | 0.9674027     |
| policy_loss        | -0.0012361417 |
| serial_timesteps   | 86272         |
| time_elapsed       | 189           |
| total_timesteps    | 86272         |
| value_loss         | 0.28131

[array([5588.])]
---------------------------------------
| approxkl           | 0.00010921801  |
| clipfrac           | 0.0            |
| explained_variance | 0.00547        |
| fps                | 479            |
| n_updates          | 689            |
| policy_entropy     | 1.0852507      |
| policy_loss        | -0.00021347101 |
| serial_timesteps   | 88192          |
| time_elapsed       | 193            |
| total_timesteps    | 88192          |
| value_loss         | 0.424847       |
---------------------------------------
[array([4000.])]
--------------------------------------
| approxkl           | 3.4683162e-05 |
| clipfrac           | 0.0           |
| explained_variance | 0.0182        |
| fps                | 426           |
| n_updates          | 690           |
| policy_entropy     | 1.1114715     |
| policy_loss        | 0.00083173066 |
| serial_timesteps   | 88320         |
| time_elapsed       | 193           |
| total_timesteps    | 88320         |
| value_loss     

[array([6541.])]
-------------------------------------
| approxkl           | 0.0012386652 |
| clipfrac           | 0.0          |
| explained_variance | -0.158       |
| fps                | 445          |
| n_updates          | 705          |
| policy_entropy     | 1.2615049    |
| policy_loss        | 0.005085427  |
| serial_timesteps   | 90240        |
| time_elapsed       | 197          |
| total_timesteps    | 90240        |
| value_loss         | 0.2973283    |
-------------------------------------
[array([4766.])]
---------------------------------------
| approxkl           | 0.000108657114 |
| clipfrac           | 0.0            |
| explained_variance | -0.0546        |
| fps                | 483            |
| n_updates          | 706            |
| policy_entropy     | 1.2592837      |
| policy_loss        | 0.0003535552   |
| serial_timesteps   | 90368          |
| time_elapsed       | 198            |
| total_timesteps    | 90368          |
| value_loss         | 0.0075426

[array([7314.])]
--------------------------------------
| approxkl           | 0.001713004   |
| clipfrac           | 0.013671875   |
| explained_variance | -1.19e-07     |
| fps                | 471           |
| n_updates          | 721           |
| policy_entropy     | 1.2408154     |
| policy_loss        | -0.0021666654 |
| serial_timesteps   | 92288         |
| time_elapsed       | 202           |
| total_timesteps    | 92288         |
| value_loss         | 0.112517245   |
--------------------------------------
[array([4596.])]
-------------------------------------
| approxkl           | 0.0017431106 |
| clipfrac           | 0.0          |
| explained_variance | -1.19e-07    |
| fps                | 427          |
| n_updates          | 722          |
| policy_entropy     | 1.2222173    |
| policy_loss        | -0.008141974 |
| serial_timesteps   | 92416        |
| time_elapsed       | 202          |
| total_timesteps    | 92416        |
| value_loss         | 0.0018906224 |
---

[array([4000.])]
--------------------------------------
| approxkl           | 0.0012703843  |
| clipfrac           | 0.0           |
| explained_variance | -1.09         |
| fps                | 468           |
| n_updates          | 737           |
| policy_entropy     | 1.2812942     |
| policy_loss        | -0.0044029085 |
| serial_timesteps   | 94336         |
| time_elapsed       | 206           |
| total_timesteps    | 94336         |
| value_loss         | 0.0067196395  |
--------------------------------------
[array([5211.])]
---------------------------------------
| approxkl           | 0.0012110822   |
| clipfrac           | 0.0            |
| explained_variance | -0.0127        |
| fps                | 494            |
| n_updates          | 738            |
| policy_entropy     | 1.2897978      |
| policy_loss        | -0.00097006315 |
| serial_timesteps   | 94464          |
| time_elapsed       | 207            |
| total_timesteps    | 94464          |
| value_loss       

[array([4487.])]
--------------------------------------
| approxkl           | 0.00092236605 |
| clipfrac           | 0.0           |
| explained_variance | 0.26          |
| fps                | 468           |
| n_updates          | 753           |
| policy_entropy     | 1.2118977     |
| policy_loss        | -0.001705267  |
| serial_timesteps   | 96384         |
| time_elapsed       | 211           |
| total_timesteps    | 96384         |
| value_loss         | 0.0039258045  |
--------------------------------------
[array([5848.])]
-------------------------------------
| approxkl           | 0.0016208787 |
| clipfrac           | 0.009765625  |
| explained_variance | -0.0101      |
| fps                | 463          |
| n_updates          | 754          |
| policy_entropy     | 1.1899399    |
| policy_loss        | -0.008617383 |
| serial_timesteps   | 96512        |
| time_elapsed       | 211          |
| total_timesteps    | 96512        |
| value_loss         | 0.0073649506 |
---

[array([5084.])]
--------------------------------------
| approxkl           | 0.002129702   |
| clipfrac           | 0.0           |
| explained_variance | 0.339         |
| fps                | 490           |
| n_updates          | 769           |
| policy_entropy     | 1.2424438     |
| policy_loss        | -0.0049430775 |
| serial_timesteps   | 98432         |
| time_elapsed       | 215           |
| total_timesteps    | 98432         |
| value_loss         | 0.0010785403  |
--------------------------------------
[array([6330.])]
--------------------------------------
| approxkl           | 0.0003055177  |
| clipfrac           | 0.0           |
| explained_variance | -0.0356       |
| fps                | 468           |
| n_updates          | 770           |
| policy_entropy     | 1.2639254     |
| policy_loss        | -8.491334e-06 |
| serial_timesteps   | 98560         |
| time_elapsed       | 215           |
| total_timesteps    | 98560         |
| value_loss         | 0.09802

[array([5804.])]
--------------------------------------
| approxkl           | 0.0015459415  |
| clipfrac           | 0.0           |
| explained_variance | -0.0017       |
| fps                | 507           |
| n_updates          | 785           |
| policy_entropy     | 1.1741132     |
| policy_loss        | -0.0037995558 |
| serial_timesteps   | 100480        |
| time_elapsed       | 219           |
| total_timesteps    | 100480        |
| value_loss         | 0.1774928     |
--------------------------------------
[array([8281.])]
--------------------------------------
| approxkl           | 0.00036032108 |
| clipfrac           | 0.0           |
| explained_variance | 0.000597      |
| fps                | 453           |
| n_updates          | 786           |
| policy_entropy     | 1.1738889     |
| policy_loss        | -0.0015030877 |
| serial_timesteps   | 100608        |
| time_elapsed       | 220           |
| total_timesteps    | 100608        |
| value_loss         | 0.32412

[array([7026.])]
--------------------------------------
| approxkl           | 0.0006979924  |
| clipfrac           | 0.0           |
| explained_variance | -0.000504     |
| fps                | 480           |
| n_updates          | 801           |
| policy_entropy     | 1.1588482     |
| policy_loss        | -0.0024463278 |
| serial_timesteps   | 102528        |
| time_elapsed       | 224           |
| total_timesteps    | 102528        |
| value_loss         | 0.14145894    |
--------------------------------------
[array([9388.])]
-------------------------------------
| approxkl           | 0.0014557198 |
| clipfrac           | 0.013671875  |
| explained_variance | 0.00339      |
| fps                | 478          |
| n_updates          | 802          |
| policy_entropy     | 1.1059325    |
| policy_loss        | -0.00585815  |
| serial_timesteps   | 102656       |
| time_elapsed       | 224          |
| total_timesteps    | 102656       |
| value_loss         | 1.8969606    |
---

[array([6464.])]
--------------------------------------
| approxkl           | 0.000640194   |
| clipfrac           | 0.0           |
| explained_variance | 0             |
| fps                | 480           |
| n_updates          | 817           |
| policy_entropy     | 0.80109334    |
| policy_loss        | -0.0012919429 |
| serial_timesteps   | 104576        |
| time_elapsed       | 228           |
| total_timesteps    | 104576        |
| value_loss         | 0.209702      |
--------------------------------------
[array([4552.])]
--------------------------------------
| approxkl           | 0.0002686057  |
| clipfrac           | 0.0           |
| explained_variance | 0             |
| fps                | 480           |
| n_updates          | 818           |
| policy_entropy     | 0.7803686     |
| policy_loss        | -0.0014695855 |
| serial_timesteps   | 104704        |
| time_elapsed       | 228           |
| total_timesteps    | 104704        |
| value_loss         | 0.00370

[array([5819.])]
--------------------------------------
| approxkl           | 0.00015982904 |
| clipfrac           | 0.0           |
| explained_variance | -0.0195       |
| fps                | 388           |
| n_updates          | 833           |
| policy_entropy     | 0.49098876    |
| policy_loss        | -0.0016396043 |
| serial_timesteps   | 106624        |
| time_elapsed       | 232           |
| total_timesteps    | 106624        |
| value_loss         | 0.4506788     |
--------------------------------------
[array([4000.])]
--------------------------------------
| approxkl           | 0.00019260801 |
| clipfrac           | 0.0           |
| explained_variance | 0             |
| fps                | 419           |
| n_updates          | 834           |
| policy_entropy     | 0.5335504     |
| policy_loss        | 5.7403813e-05 |
| serial_timesteps   | 106752        |
| time_elapsed       | 233           |
| total_timesteps    | 106752        |
| value_loss         | 2.36914

[array([4048.])]
--------------------------------------
| approxkl           | 0.00041940773 |
| clipfrac           | 0.001953125   |
| explained_variance | 0             |
| fps                | 466           |
| n_updates          | 849           |
| policy_entropy     | 0.64147395    |
| policy_loss        | -0.0029788846 |
| serial_timesteps   | 108672        |
| time_elapsed       | 237           |
| total_timesteps    | 108672        |
| value_loss         | 0.0056158234  |
--------------------------------------
[array([4546.])]
--------------------------------------
| approxkl           | 0.00022723088 |
| clipfrac           | 0.0           |
| explained_variance | 0             |
| fps                | 471           |
| n_updates          | 850           |
| policy_entropy     | 0.6920029     |
| policy_loss        | 0.00052068615 |
| serial_timesteps   | 108800        |
| time_elapsed       | 237           |
| total_timesteps    | 108800        |
| value_loss         | 0.00412

[array([4284.])]
-------------------------------------
| approxkl           | 0.0003365841 |
| clipfrac           | 0.0          |
| explained_variance | -0.0436      |
| fps                | 495          |
| n_updates          | 865          |
| policy_entropy     | 0.6073363    |
| policy_loss        | -0.00211112  |
| serial_timesteps   | 110720       |
| time_elapsed       | 241          |
| total_timesteps    | 110720       |
| value_loss         | 0.047542084  |
-------------------------------------
[array([4851.])]
--------------------------------------
| approxkl           | 0.00073788426 |
| clipfrac           | 0.017578125   |
| explained_variance | -0.00321      |
| fps                | 480           |
| n_updates          | 866           |
| policy_entropy     | 0.6233261     |
| policy_loss        | -0.0029131554 |
| serial_timesteps   | 110848        |
| time_elapsed       | 242           |
| total_timesteps    | 110848        |
| value_loss         | 0.34067643    |
----

[array([4048.])]
--------------------------------------
| approxkl           | 0.00012606021 |
| clipfrac           | 0.0           |
| explained_variance | 0             |
| fps                | 478           |
| n_updates          | 881           |
| policy_entropy     | 0.44914258    |
| policy_loss        | -0.0020884355 |
| serial_timesteps   | 112768        |
| time_elapsed       | 246           |
| total_timesteps    | 112768        |
| value_loss         | 0.23788682    |
--------------------------------------
[array([5273.])]
--------------------------------------
| approxkl           | 0.0006764438  |
| clipfrac           | 0.0           |
| explained_variance | 0.000346      |
| fps                | 490           |
| n_updates          | 882           |
| policy_entropy     | 0.3976472     |
| policy_loss        | -0.0014353688 |
| serial_timesteps   | 112896        |
| time_elapsed       | 246           |
| total_timesteps    | 112896        |
| value_loss         | 0.70462

[array([4338.])]
--------------------------------------
| approxkl           | 0.00033784204 |
| clipfrac           | 0.0           |
| explained_variance | 0             |
| fps                | 486           |
| n_updates          | 897           |
| policy_entropy     | 0.58667       |
| policy_loss        | 0.0027436302  |
| serial_timesteps   | 114816        |
| time_elapsed       | 250           |
| total_timesteps    | 114816        |
| value_loss         | 0.70743513    |
--------------------------------------
[array([5338.])]
-------------------------------------
| approxkl           | 1.280919e-05 |
| clipfrac           | 0.0          |
| explained_variance | 1.79e-07     |
| fps                | 493          |
| n_updates          | 898          |
| policy_entropy     | 0.5883293    |
| policy_loss        | 6.010325e-05 |
| serial_timesteps   | 114944       |
| time_elapsed       | 250          |
| total_timesteps    | 114944       |
| value_loss         | 0.17244247   |
---

[array([5027.])]
--------------------------------------
| approxkl           | 0.0016835204  |
| clipfrac           | 0.033203125   |
| explained_variance | 0             |
| fps                | 477           |
| n_updates          | 913           |
| policy_entropy     | 0.7673504     |
| policy_loss        | -0.0018884058 |
| serial_timesteps   | 116864        |
| time_elapsed       | 254           |
| total_timesteps    | 116864        |
| value_loss         | 0.012743675   |
--------------------------------------
[array([6089.])]
--------------------------------------
| approxkl           | 0.0006251453  |
| clipfrac           | 0.0           |
| explained_variance | 0             |
| fps                | 456           |
| n_updates          | 914           |
| policy_entropy     | 0.76644534    |
| policy_loss        | -0.0019063813 |
| serial_timesteps   | 116992        |
| time_elapsed       | 254           |
| total_timesteps    | 116992        |
| value_loss         | 0.20537

[array([5228.])]
--------------------------------------
| approxkl           | 0.00030225885 |
| clipfrac           | 0.0           |
| explained_variance | 0.0206        |
| fps                | 485           |
| n_updates          | 929           |
| policy_entropy     | 0.82936597    |
| policy_loss        | -0.0030644615 |
| serial_timesteps   | 118912        |
| time_elapsed       | 258           |
| total_timesteps    | 118912        |
| value_loss         | 2.3863313     |
--------------------------------------
[array([4208.])]
--------------------------------------
| approxkl           | 0.00049921626 |
| clipfrac           | 0.0           |
| explained_variance | 0             |
| fps                | 464           |
| n_updates          | 930           |
| policy_entropy     | 0.7906481     |
| policy_loss        | -0.0007402252 |
| serial_timesteps   | 119040        |
| time_elapsed       | 259           |
| total_timesteps    | 119040        |
| value_loss         | 0.11937

[array([6700.])]
---------------------------------------
| approxkl           | 0.000113695096 |
| clipfrac           | 0.0            |
| explained_variance | -2.38e-07      |
| fps                | 469            |
| n_updates          | 945            |
| policy_entropy     | 0.8564686      |
| policy_loss        | 0.0017449616   |
| serial_timesteps   | 120960         |
| time_elapsed       | 263            |
| total_timesteps    | 120960         |
| value_loss         | 2.5051844      |
---------------------------------------
[array([4007.])]
--------------------------------------
| approxkl           | 7.4570016e-05 |
| clipfrac           | 0.0           |
| explained_variance | 0             |
| fps                | 493           |
| n_updates          | 946           |
| policy_entropy     | 0.86107373    |
| policy_loss        | -0.00121689   |
| serial_timesteps   | 121088        |
| time_elapsed       | 263           |
| total_timesteps    | 121088        |
| value_loss     

[array([8161.])]
---------------------------------------
| approxkl           | 0.00019154596  |
| clipfrac           | 0.0            |
| explained_variance | 0.000704       |
| fps                | 491            |
| n_updates          | 961            |
| policy_entropy     | 0.97444487     |
| policy_loss        | -0.00016285607 |
| serial_timesteps   | 123008         |
| time_elapsed       | 267            |
| total_timesteps    | 123008         |
| value_loss         | 2.143388       |
---------------------------------------
[array([5000.])]
-------------------------------------
| approxkl           | 0.0021988312 |
| clipfrac           | 0.021484375  |
| explained_variance | -0.00314     |
| fps                | 494          |
| n_updates          | 962          |
| policy_entropy     | 0.94572175   |
| policy_loss        | -0.008522942 |
| serial_timesteps   | 123136       |
| time_elapsed       | 268          |
| total_timesteps    | 123136       |
| value_loss         | 0.522

[array([4000.])]
--------------------------------------
| approxkl           | 0.00037179264 |
| clipfrac           | 0.0           |
| explained_variance | 0.0208        |
| fps                | 466           |
| n_updates          | 977           |
| policy_entropy     | 1.1360694     |
| policy_loss        | 0.00042546308 |
| serial_timesteps   | 125056        |
| time_elapsed       | 272           |
| total_timesteps    | 125056        |
| value_loss         | 0.14175059    |
--------------------------------------
[array([5467.])]
--------------------------------------
| approxkl           | 0.0013826699  |
| clipfrac           | 0.009765625   |
| explained_variance | 0.0537        |
| fps                | 500           |
| n_updates          | 978           |
| policy_entropy     | 1.0911342     |
| policy_loss        | -0.0066698287 |
| serial_timesteps   | 125184        |
| time_elapsed       | 272           |
| total_timesteps    | 125184        |
| value_loss         | 1.18362

[array([5034.])]
--------------------------------------
| approxkl           | 0.0010148311  |
| clipfrac           | 0.001953125   |
| explained_variance | 0             |
| fps                | 469           |
| n_updates          | 993           |
| policy_entropy     | 0.97933203    |
| policy_loss        | -0.0023423969 |
| serial_timesteps   | 127104        |
| time_elapsed       | 276           |
| total_timesteps    | 127104        |
| value_loss         | 0.057678398   |
--------------------------------------
[array([5818.])]
--------------------------------------
| approxkl           | 0.0019352388  |
| clipfrac           | 0.0390625     |
| explained_variance | 0             |
| fps                | 495           |
| n_updates          | 994           |
| policy_entropy     | 0.99648076    |
| policy_loss        | -0.0076023745 |
| serial_timesteps   | 127232        |
| time_elapsed       | 276           |
| total_timesteps    | 127232        |
| value_loss         | 0.05117

[array([5000.])]
--------------------------------------
| approxkl           | 8.708168e-05  |
| clipfrac           | 0.0           |
| explained_variance | 0.0011        |
| fps                | 484           |
| n_updates          | 1009          |
| policy_entropy     | 1.0784315     |
| policy_loss        | -0.0010705945 |
| serial_timesteps   | 129152        |
| time_elapsed       | 280           |
| total_timesteps    | 129152        |
| value_loss         | 1.8224745     |
--------------------------------------
[array([5000.])]
-------------------------------------
| approxkl           | 0.0010215958 |
| clipfrac           | 0.0          |
| explained_variance | 0.00208      |
| fps                | 471          |
| n_updates          | 1010         |
| policy_entropy     | 1.1229233    |
| policy_loss        | -0.004300418 |
| serial_timesteps   | 129280       |
| time_elapsed       | 281          |
| total_timesteps    | 129280       |
| value_loss         | 2.6934655    |
---

[array([5328.])]
---------------------------------------
| approxkl           | 0.0004027713   |
| clipfrac           | 0.0            |
| explained_variance | 0              |
| fps                | 435            |
| n_updates          | 1025           |
| policy_entropy     | 1.3368064      |
| policy_loss        | -0.00017288479 |
| serial_timesteps   | 131200         |
| time_elapsed       | 285            |
| total_timesteps    | 131200         |
| value_loss         | 0.6035655      |
---------------------------------------
[array([7328.])]
--------------------------------------
| approxkl           | 0.000311972   |
| clipfrac           | 0.0           |
| explained_variance | 0             |
| fps                | 459           |
| n_updates          | 1026          |
| policy_entropy     | 1.3359166     |
| policy_loss        | -0.0010382526 |
| serial_timesteps   | 131328        |
| time_elapsed       | 285           |
| total_timesteps    | 131328        |
| value_loss     

[array([6791.])]
--------------------------------------
| approxkl           | 0.0005841878  |
| clipfrac           | 0.0           |
| explained_variance | 0.0863        |
| fps                | 457           |
| n_updates          | 1041          |
| policy_entropy     | 1.3008953     |
| policy_loss        | -0.0014718252 |
| serial_timesteps   | 133248        |
| time_elapsed       | 289           |
| total_timesteps    | 133248        |
| value_loss         | 1.9202807     |
--------------------------------------
[array([7316.])]
--------------------------------------
| approxkl           | 0.0002193414  |
| clipfrac           | 0.0           |
| explained_variance | -0.251        |
| fps                | 462           |
| n_updates          | 1042          |
| policy_entropy     | 1.2901299     |
| policy_loss        | -0.0013699658 |
| serial_timesteps   | 133376        |
| time_elapsed       | 289           |
| total_timesteps    | 133376        |
| value_loss         | 0.45268

KeyboardInterrupt: 

In [ ]:
#help(model)

def callback(locs, globs):
    hlt = globs['env'].env_method('pl_halite')
    tf.summary.scalar('Player halite', hlt)
    return True

#callback(locals(), globals())

glob = globals()
glob['env'].env_method('pl_halite')

In [ ]:
print(
        "Took {:.2f}s for training - {:.2f} FPS".format(
            total_time_single, n_timesteps / total_time_single
        )
    )

mean_reward = evaluate(model, num_steps=10000)

In [ ]:
obs = env.reset()
for i in range(1000):
    action, _states = model.predict(obs)
    obs, rewards, dones, info = env.step(action)
    env.render()


In [ ]:
#obs = env.reset()
action, _states = model.predict(obs)
obs, rewards, dones, info = env.step(action)
print(obs)
#print(action)

In [ ]:
model.save("halite")
del model
model = PPO2.load("halite", env=env)


In [ ]:
env = Single_ship_env_initialization(map_size)

In [ ]:
env.reset()
for i in range(420):
    ob = env.step(env.action_space.sample())
print(ob)

In [ ]:
env.step(env.action_space.sample())
#env.reset()


In [ ]:
x = gym.spaces.Discrete(4)

In [ ]:
x.sample()

In [ ]:
import time
from random import uniform
from IPython.display import display, clear_output

i = 1
for _ in range(200):
    clear_output(wait=True)
    display('Iteration '+str(i)+' Score: '+str(uniform(0, 1)))
    time.sleep(0.1)
    i += 1